name: continuos_integration

on: 
  push :
    branches : 
      - dev
  pull_request : 
    branches : 
      - main
  workflow_dispatch:

jobs: 
  Server-tests:
    runs-on: windows-latest
    name: Running unit tests on server side
    steps: 
      - uses: actions/checkout@v2
        name: 'checkout repository'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 'Install Dependencies'
        working-directory: Server
        run : npm install

      - name: 'run tests'
        working-directory: Server
        run: npm run test

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push server Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Server
          file: ./Server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/server-image:latest

      - name: Build and push client Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Client
          file: ./Client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/client-image:latest
      

